[package]
name = "plugin_example"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
log = "0.4"
alumet = { path = "../../../ALUMET-git/alumet" }
serde = { version = "1.0.217", features = ["derive"] }
humantime-serde = "1.1.1"
